Load the data set

In [2]:
import numpy as np

def loadData(data_set = None):

    if (data_set == None):
        return None
    else:
        data = []
        fptr = open(data_set, "r")
        lines = fptr.readlines()
        for line in lines:
            line = line.strip().split()
            # if (line[-1] == -1):
            #     continue
            for i in range(len(line)):
                line[i] = float(line[i])
            # print(line)
            data.append(line)
        
        return data

data_set = loadData("5_11/visual_annotion_5_11.txt")

In [3]:
data_set = np.array(data_set)

In [10]:
print(data_set[:5])

[[-67.  13.  11.   0.]
 [-61.  17.  23.   0.]
 [-65.  18.  25.   0.]
 [-58.  20.  25.   0.]
 [-58.  20.  21.   0.]]


In [4]:
X = data_set[:, :-1]
y = data_set[:, -1]

# print(X[:5], Y[:5], data_set[:5])

Utility function that are used in every model

In [5]:
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error

def printMetrics(y_test, y_pred):
    print("Accuracy: ", accuracy_score(y_pred, y_test)*100)
    print("Mean Squared Error: ", mean_squared_error(y_pred, y_test))
    print("Mean Absolute Error: ", mean_absolute_error(y_pred, y_test))

Splitting the data set

In [6]:
from sklearn.model_selection import train_test_split

# splitting the data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Model-1 Descision tree

In [15]:
# Importing libraries 
from sklearn.tree import DecisionTreeClassifier

# Model training
model_1 = DecisionTreeClassifier()
model_1.fit(X_train, y_train)

y_pred = model_1.predict(X_test)
printMetrics(y_test, y_pred)

Accuracy:  73.13364055299539
Mean Squared Error:  0.36820276497695853
Mean Absolute Error:  0.30184331797235026


Model-2 Random Forest

In [16]:
from sklearn.ensemble import RandomForestClassifier

model_2 = RandomForestClassifier()
model_2.fit(X_train, y_train)

y_pred = model_2.predict(X_test)
printMetrics(y_test, y_pred)

Accuracy:  77.64976958525345
Mean Squared Error:  0.29539170506912443
Mean Absolute Error:  0.24746543778801844


Model-3 K-Nearest Neighbour

In [17]:
from sklearn.neighbors import KNeighborsClassifier

model_3 = KNeighborsClassifier(n_neighbors=5)
model_3.fit(X_train, y_train)

y_pred = model_3.predict(X_test)
printMetrics(y_test, y_pred)

Accuracy:  78.89400921658986
Mean Squared Error:  0.280184331797235
Mean Absolute Error:  0.23410138248847925


Model-4 ANN

Individual Class Accuracy

In [23]:
X_true = []
Y_true = []
X_false = []
Y_false = []

for i in range(len(data_set)):
    
    if data_set[i, -1] == 1:
        X_true.append(data_set[i, :-1])
        Y_true.append(data_set[i, -1])
    else:
        X_false.append(data_set[i, :-1])
        Y_false.append(data_set[i, -1])

# print(data_set[:5], X_false[:5])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model 1: Descision tree
print("for True value\n")

print("Model: 1 Descison tree")
y_pred = model_1.predict(X_true)
printMetrics(y_pred, Y_true)

# Model: 2 Random Forest
print("\nModel: 2 Random Forest")
y_pred = model_2.predict(X_true)
printMetrics(y_pred, Y_true)

# Model: 3 K-Nearest Neighbour
print("\nModel:3 K-Nearest Neighbour")
y_pred = model_3.predict(X_true)
printMetrics(y_pred, Y_true)

print("----------\nFor False value")
print("\nModel: 1 Descison tree")
y_pred = model_1.predict(X_false)
printMetrics(y_pred, Y_false)

# Model: 2 Random Forest
print("\nModel: 2 Random Forest")
y_pred = model_2.predict(X_false)
printMetrics(y_pred, Y_false)

# Model: 3 K-Nearest Neighbour
print("\nModel:3 K-Nearest Neighbour")
y_pred = model_3.predict(X_false)
printMetrics(y_pred, Y_false)

for True value

Model: 1 Descison tree
Accuracy:  91.04271933853929
Mean Squared Error:  0.11208084519981626
Mean Absolute Error:  0.09707548614301026

Model: 2 Random Forest
Accuracy:  94.82468228448936
Mean Squared Error:  0.05956208850099525
Mean Absolute Error:  0.05435614760373603

Model:3 K-Nearest Neighbour
Accuracy:  90.01684274996173
Mean Squared Error:  0.12509569744296434
Mean Absolute Error:  0.1082529474812433
----------
For False value

Model: 1 Descison tree
Accuracy:  92.23998146861247
Mean Squared Error:  0.10956682881630762
Mean Absolute Error:  0.08825573314801946

Model: 2 Random Forest
Accuracy:  88.7653463053046
Mean Squared Error:  0.15334723187398658
Mean Absolute Error:  0.12601343525596478

Model:3 K-Nearest Neighbour
Accuracy:  75.09844799629373
Mean Squared Error:  0.3574241371322678
Mean Absolute Error:  0.28515172573546443
