In [41]:
import numpy as np
from scipy.signal import stft

In [42]:
def loadData(data_set = None):

    if (data_set == None):
        return None
    else:
        data = []
        fptr = open(data_set, "r")
        lines = fptr.readlines()
        for line in lines:
            line = line.strip().split()
            for i in range(len(line)):
                line[i] = float(line[i])
            # print(line)
            data.append(line)
        
        return np.array(data)

In [129]:
def giveFreqCoeff(data_set):
    
    x = data_set[:, 0]
    y = data_set[:, 1]
    z = data_set[:, 2]

    fs = 32
    seg_size = 32
    hop_size = seg_size // 2

    f_x, t_x, Zxx_x = stft(x, fs, nperseg=seg_size, noverlap=hop_size)
    f_y, t_y, Zxx_y = stft(y, fs, nperseg=seg_size, noverlap=hop_size)
    f_z, t_z, Zxx_z = stft(z, fs, nperseg=seg_size, noverlap=hop_size)

    # Magnitude of frequency coefficients for X, Y, Z-axis
    freq_coeffs_x = np.abs(Zxx_x)  
    freq_coeffs_y = np.abs(Zxx_y)  
    freq_coeffs_z = np.abs(Zxx_z)  

    freq_coeffs_x = np.mean(freq_coeffs_x, axis=0)
    freq_coeffs_y = np.mean(freq_coeffs_y, axis=0)
    freq_coeffs_z = np.mean(freq_coeffs_z, axis=0)

    return freq_coeffs_x, freq_coeffs_y, freq_coeffs_z


In [130]:
def mergeDataset(data_set, fc_x, fc_y, fc_z):

    new_data_set = []
    length = len(data_set) // 32
    min_lenght = min(length, len(fc_x))

    k = 0
    for i in range(len(data_set), 32):

        for j in range(32):

            if i + j > len(data_set) or k > len(fc_x):
                break

            temp = []
            temp.append(data_set[i + j][0])
            temp.append(data_set[i + j][1])
            temp.append(data_set[i + j][2])
            temp.append(fc_x[k])
            temp.append(fc_y[k])
            temp.append(fc_z[k])

            new_data_set.append(temp)

        k += 1

    
    return new_data_set


        

In [131]:
data_set_1 = loadData("5_11/visual_annotion_5_11.txt")

In [132]:
freq_coeffs_x, freq_coeffs_y, freq_coeffs_z = giveFreqCoeff(data_set_1)

In [134]:
print(freq_coeffs_x[:5])

[6.90520891 5.63900307 5.48786121 5.3780034  5.44275766]


In [135]:
x = data_set_1[:, 0]
y = data_set_1[:, 1]
z = data_set_1[:, 2]

fs = 32
seg_size = 32
hop_size = seg_size // 2

f_x, t_x, Zxx_x = stft(x, fs, nperseg=seg_size, noverlap=hop_size)
f_y, t_y, Zxx_y = stft(y, fs, nperseg=seg_size, noverlap=hop_size)
f_z, t_z, Zxx_z = stft(z, fs, nperseg=seg_size, noverlap=hop_size)

In [136]:
# Magnitude of frequency coefficients for X, Y, Z-axis
freq_coeffs_x = np.abs(Zxx_x)  
freq_coeffs_y = np.abs(Zxx_y)  
freq_coeffs_z = np.abs(Zxx_z)  

(1397,)

In [138]:
freq_coeffs_x = np.mean(freq_coeffs_x, axis=0)


In [139]:
freq_coeffs_x[:10]

array([6.90520891, 5.63900307, 5.48786121, 5.3780034 , 5.44275766,
       6.02830456, 5.02156329, 4.64820687, 4.4404538 , 3.71434727])

In [42]:
print(x, freq_coeffs_x)

[-0.25961899  0.38714278 -0.59462572 ...  0.02012856  2.98186382
 -0.37143739] [[0.12698784 0.0495531  0.10002736 ... 0.02178528 0.14104729 0.00299342]
 [0.11567441 0.04166631 0.09738974 ... 0.16406773 0.22797895 0.05506835]
 [0.08274473 0.0964906  0.11445873 ... 0.14021225 0.14410543 0.07773322]
 ...
 [0.03408262 0.1867545  0.0890008  ... 0.11873832 0.0926552  0.04138756]
 [0.0297205  0.22842615 0.0494959  ... 0.18131414 0.13060486 0.07925463]
 [0.01005903 0.26131465 0.01842983 ... 0.19528973 0.16200093 0.12032045]]


In [45]:
len(x)

3200

In [50]:
len(freq_coeffs_x[50])

65

In [51]:
print("Shape of Zxx:", Zxx_x.shape)

Shape of Zxx: (51, 65)


In [53]:
f

array([ 0.  ,  0.32,  0.64,  0.96,  1.28,  1.6 ,  1.92,  2.24,  2.56,
        2.88,  3.2 ,  3.52,  3.84,  4.16,  4.48,  4.8 ,  5.12,  5.44,
        5.76,  6.08,  6.4 ,  6.72,  7.04,  7.36,  7.68,  8.  ,  8.32,
        8.64,  8.96,  9.28,  9.6 ,  9.92, 10.24, 10.56, 10.88, 11.2 ,
       11.52, 11.84, 12.16, 12.48, 12.8 , 13.12, 13.44, 13.76, 14.08,
       14.4 , 14.72, 15.04, 15.36, 15.68, 16.  ])

In [54]:
t

array([  0.    ,   1.5625,   3.125 ,   4.6875,   6.25  ,   7.8125,
         9.375 ,  10.9375,  12.5   ,  14.0625,  15.625 ,  17.1875,
        18.75  ,  20.3125,  21.875 ,  23.4375,  25.    ,  26.5625,
        28.125 ,  29.6875,  31.25  ,  32.8125,  34.375 ,  35.9375,
        37.5   ,  39.0625,  40.625 ,  42.1875,  43.75  ,  45.3125,
        46.875 ,  48.4375,  50.    ,  51.5625,  53.125 ,  54.6875,
        56.25  ,  57.8125,  59.375 ,  60.9375,  62.5   ,  64.0625,
        65.625 ,  67.1875,  68.75  ,  70.3125,  71.875 ,  73.4375,
        75.    ,  76.5625,  78.125 ,  79.6875,  81.25  ,  82.8125,
        84.375 ,  85.9375,  87.5   ,  89.0625,  90.625 ,  92.1875,
        93.75  ,  95.3125,  96.875 ,  98.4375, 100.    , 101.5625,
       103.125 , 104.6875, 106.25  , 107.8125, 109.375 , 110.9375,
       112.5   , 114.0625, 115.625 , 117.1875, 118.75  , 120.3125,
       121.875 , 123.4375, 125.    , 126.5625, 128.125 , 129.6875,
       131.25  , 132.8125, 134.375 , 135.9375, 137.5   , 139.0